[workspace]
resolver = "2"
members = ["bin/admin-pannel-api"]

[workspace.dependencies]
tokio = "1"
clap = "4.4"
log = "0.4"
tracing-subscriber = "0.3"
serde = "1.0"
serde_json = "1.0"
env_logger = "0.11"
anyhow = "1"
parking_lot = "0.12"
poem = "3.1.3"
poem-openapi = "5.1.2"
