[target.aarch64-unknown-linux-gnu]
# Install libssl-dev:arm64, nodejs and pnpm
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install libssl-dev:$CROSS_DEB_ARCH curl",
    "curl -fsSL https://deb.nodesource.com/setup_22.x | bash -",
    "apt-get install -y nodejs",
    "npm install -g pnpm@8"
]