[target.aarch64-unknown-linux-gnu]
# Install libssl-dev:arm64
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install libssl-dev:$CROSS_DEB_ARCH curl",
]

[build.env]
passthrough = [
    "RUST_BACKTRACE",
    "RUST_LOG",
    "SKIP_FRONTEND_BUILD",
]