[package]
name = "admin-panel"
version = "0.1.0"
edition = "2021"

[dependencies]
http-common = { path = "../../packages/http-common" }
atm0s-media-cloud-utils = { path = "../../packages/utils" }
tokio = { workspace = true, features = ["full"] }
clap = { workspace = true, features = ["derive", "env"] }
log = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "std"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
env_logger = { workspace = true }
anyhow = { workspace = true }
poem = { workspace = true, features = ["session"] }
poem-openapi = { workspace = true }
rust-embed = { workspace = true }
welds = { workspace = true, features = ["migrations", "check", "sqlite", "postgres", "mysql"] }
sqlx = { workspace = true, features = ["runtime-tokio", "chrono"] }
uuid = { workspace = true, features = ["v4"] }
chrono = { workspace = true, features = ["serde"] }
jsonwebtoken = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
clerk-rs = { workspace = true }
bcrypt = { workspace = true }
oauth2 = { workspace = true }

[[bin]]
name = "server"
path = "bin/server.rs"