[package]
name = "admin-panel"
version = "0.1.0"
edition = "2021"

[dependencies]
http-common = { path = "../../packages/http-common" }
tokio = { workspace = true, features = ["full"] }
clap = { workspace = true, features = ["derive", "env"] }
log = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "std"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
env_logger = { workspace = true }
anyhow = { workspace = true }
poem = { workspace = true }
poem-openapi = { workspace = true }
rust-embed = { workspace = true }

[[bin]]
name = "server"
path = "bin/server.rs"